❇️ 定义 git `Authorization` header
abersheeran/sync-gitee-mirror pull request #1
Opened 2021-07-24 09:09 UTC by Shuliyey

* ❇️ 定义 git `Authorization` header
* 文档 更改 "密码尽量避免 bash 特殊字符"

2021-07-24 13:51 UTC, abersheeran commented
> 定义 git Authorization header

这个目的是什么？

2021-07-25 01:05 UTC, Shuliyey commented
> > 定义 git Authorization header
> 
> 这个目的是什么？

不设置`Authorization` Header (`git config http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n "x-access-token:${{ inputs.token }}" | base64)"`) 的情况下 `git fetch --all` github 会报错

![image](https://user-images.githubusercontent.com/4773348/126884509-6132fc1c-5e43-460c-ac41-7f28f8a1f952.png)

2021-07-25 12:33 UTC, abersheeran commented
https://github.com/abersheeran/usefuls/blob/master/.github/workflows/mirror.yml

我没有重现你的问题。能不能给出你的仓库地址或者 yaml 文件的相关部分？

2021-07-25 12:40 UTC, Shuliyey commented
> https://github.com/abersheeran/usefuls/blob/master/.github/workflows/mirror.yml
> 
> 我没有重现你的问题。能不能给出你的仓库地址或者 yaml 文件的相关部分？

https://github.com/Shuliyey/usefuls/runs/3154759976

2021-07-25 12:43 UTC, Shuliyey commented
> https://github.com/abersheeran/usefuls/blob/master/.github/workflows/mirror.yml
> 
> 我没有重现你的问题。能不能给出你的仓库地址或者 yaml 文件的相关部分？

我的是 private repo 所以会需要`github.token` 去fetch, public repo 由于不需要token 也可以fetch

2021-07-25 12:45 UTC, abersheeran commented
好，明白了。

2021-07-25 12:46 UTC, abersheeran requested changes

2021-07-25 12:46 UTC, abersheeran commented on action.yml
> +    description: 'GIthub 令牌, 用于获取。'
修改措辞和拼写：“GitHub 令牌，用于私有仓库的拉取。”

2021-07-25 12:46 UTC, abersheeran commented on README.md
> +- `password`：填写你的 gitee 密码（注意：密码需要以 [Secrets](https://docs.github.com/cn/actions/reference/encrypted-secrets) 方式给出，以保证密码不被泄露, 同时尽量确保密码避免 bash 特殊字符 `` !'"`@ `` 等等）
逗号应当是全角中文符号。

2021-07-25 12:53 UTC, Shuliyey commented on action.yml
> +    description: 'GIthub 令牌, 用于获取。'
https://github.com/abersheeran/sync-gitee-mirror/pull/1/commits/171339d5333462909040ba32e125b754f2230c9a

2021-07-25 12:53 UTC, Shuliyey commented on README.md
> +- `password`：填写你的 gitee 密码（注意：密码需要以 [Secrets](https://docs.github.com/cn/actions/reference/encrypted-secrets) 方式给出，以保证密码不被泄露, 同时尽量确保密码避免 bash 特殊字符 `` !'"`@ `` 等等）
https://github.com/abersheeran/sync-gitee-mirror/pull/1/commits/171339d5333462909040ba32e125b754f2230c9a

2021-07-25 12:54 UTC, abersheeran approved these changes

2021-07-25 12:55 UTC, merged

2021-07-25 12:58 UTC, abersheeran commented
感谢你的 PR。https://github.com/abersheeran/sync-gitee-mirror/releases/tag/v1-beta 已经发布新版本